#!/usr/bin/env python3
"""The two drift tables §4.3 prints, regenerated by the exact route, with an artifact on disk.

    python experiments/2026-07-26-sw02-exchangeability-audit/drift_tables.py

WHY THIS EXISTS
§4.3 prints two tables. Re-verifying them on 2026-07-31 found:

  * Table 1 (b sweep) is CORRECT to all six decimals, but no results file on disk contained it.
    `prop1_exact.py`'s stored run is a different configuration — the atom mixture and a one-factor
    Gaussian at rho=0.40 — so the paper's table was reproducible only by someone who knew to
    re-run with r=0.7881.
  * Table 2 (four configurations, "tested where it was not tuned") is a MONTE CARLO table printed
    without its standard errors, directly after a table introduced as "computed, not sampled, and
    carries no standard error". It comes from `drift_coefficient.py` section [2] and reproduces
    exactly from it. Its four rows sit 1.07, 1.60, 1.73 and 1.97 sigma from the prediction — all
    on the same side, which is a 1-in-16 coincidence and not a defect. But with the sigmas
    omitted and an exact table immediately above, a reader reads those 96-99% ratios as the
    accuracy of Proposition 1, when they are the noise of the estimator measuring it.

Regenerating Table 2 exactly removes the ambiguity: same four configurations, no sampling error, a
stated b. Proposition 1 then holds to 0.17%, against the 96-99% the sampled table appeared to show.
`drift_coefficient.py` remains the independent simulated route and is now named in §12 beside this.

WHAT IS COMPUTED
Coverage is the k-th order statistic of the probability-transformed scores, so
E[C] = int_0^1 P(N(t) <= k-1) dt is an exact identity; for a specified cluster model the
single-cluster pmf, the b-fold convolution and the outer integral are all deterministic. This is
§4.3's machinery, imported from prop1_exact.py rather than reimplemented, so a bug here is a bug
there too. No Monte Carlo, no standard errors.

PRECONDITIONS, all of which can fail
  1. Independent clusters must return E[C] = k/(n+1) to machine precision (prop1_exact's own
     control, re-run here rather than assumed).
  2. KNOWN BOUNDS. Table 1's five published rows are asserted before Table 2 is computed at all.
     Machinery that cannot reproduce the table already known to be right has no standing to
     replace the one being restated.
  3. The copula tuning must hit each target rho_I to 1e-9, since "rho_I = 0.25" is the row label
     and a mistuned copula would silently relabel the row.
"""
import sys
from pathlib import Path

import numpy as np
from scipy.optimize import brentq

sys.path.insert(0, str(Path(__file__).resolve().parent))
from prop1_exact import (cluster_pmf_gauss, exact_EC, precondition,  # noqa: E402
                         predicted_drift, rho_I_gauss, rho_I_prime)

# Table 1 — the configuration §4.3 names: p = 0.90, m = 4, rho_I = 0.5.
T1_M, T1_R, T1_P = 4, 0.7881, 0.90
T1_BS = (25, 50, 100, 200, 400)
T1_PUBLISHED = {25: -0.1698, 50: -0.1709, 100: -0.1715, 200: -0.1718, 400: -0.1720}

# Table 2 — four configurations, no free parameter. b is FIXED and stated here; the printed
# table never stated one, which is why its sampling error could not be read off it.
T2_B = 400
T2_ROWS = [(4, 0.90, 0.25), (8, 0.90, 0.50), (4, 0.95, 0.50), (2, 0.90, 0.60)]


def tune(p, target_rho_I):
    """Gaussian within-cluster correlation r such that rho_I(p) == target."""
    r = brentq(lambda x: float(np.atleast_1d(rho_I_gauss(p, x))[0]) - target_rho_I,
               1e-9, 1 - 1e-9, xtol=1e-14)
    got = float(np.atleast_1d(rho_I_gauss(p, r))[0])
    return r, got


def drift_at(m, r, b, target_p):
    n = b * m
    k = int(round(target_p * (n + 1)))
    p = k / (n + 1.0)
    ec = exact_EC(lambda t: cluster_pmf_gauss(t, m, r), lambda t: rho_I_gauss(t, r), b, m, k)
    pred = predicted_drift(lambda t: rho_I_gauss(t, r), n, m, p)
    return n, k, p, ec - p, pred


def main() -> int:
    print("=" * 96)
    print("§4.3's DRIFT TABLES — exact, no Monte Carlo")
    print("=" * 96)

    if not precondition():
        print("\nSTOP: the exact pipeline cannot reproduce the exchangeable case.")
        return 1

    # ---------------------------------------------------------------- Table 1
    print(f"\n[1] TABLE 1 — one-factor Gaussian r = {T1_R}, m = {T1_M}, target p = {T1_P}")
    for probe in (0.90, 0.9005):
        rI = float(np.atleast_1d(rho_I_gauss(probe, T1_R))[0])
        rIp = rho_I_prime(lambda t: rho_I_gauss(t, T1_R), probe)
        print(f"    at p = {probe:.4f}:  rho_I = {rI:.4f}   rho_I' = {rIp:.4f}"
              f"{'   <- the pair §4.3 quotes' if probe == 0.90 else ''}")
    print(f"    {'b':>5} {'n':>6} {'p':>9} {'drift':>12} {'b*drift':>10} {'predicted':>10} "
          f"{'published':>10} {'delta':>9}")
    ok = True
    for b in T1_BS:
        n, k, p, d, pred = drift_at(T1_M, T1_R, b, T1_P)
        pub = T1_PUBLISHED[b]
        delta = b * d - pub
        ok &= abs(delta) < 5e-4
        print(f"    {b:>5} {n:>6} {p:>9.5f} {d:>12.6f} {b*d:>10.4f} {b*pred:>10.4f} "
              f"{pub:>10.4f} {delta:>+9.5f}")
    print(f"    -> PRECONDITION 2 (known bounds): {'PASS' if ok else 'FAIL'} — the published "
          f"table reproduces")
    if not ok:
        print("    STOP: cannot reproduce the table verification confirmed; Table 2 is not computed.")
        return 1

    # ---------------------------------------------------------------- Table 2
    print(f"\n[2] TABLE 2 — four configurations at a FIXED, STATED b = {T2_B}")
    print("    Replaces a Monte Carlo table (drift_coefficient.py [2]) printed without its")
    print("    standard errors, whose rows sat 1.07-1.97 sigma below prediction — noise that read")
    print("    as a 1-4% shortfall in Proposition 1's accuracy.")
    print(f"    {'m':>3} {'target p':>9} {'rho_I':>7} {'gauss r':>9} {'tuning err':>11} "
          f"{'b*drift':>10} {'predicted':>10} {'ratio':>8}")
    worst = 0.0
    for m, tgt, target_rI in T2_ROWS:
        n = T2_B * m
        k = int(round(tgt * (n + 1)))
        p = k / (n + 1.0)
        r, got = tune(p, target_rI)
        err = abs(got - target_rI)
        if err > 1e-9:
            print(f"    STOP: copula tuning missed rho_I = {target_rI} by {err:.2e}")
            return 1
        _, _, _, d, pred = drift_at(m, r, T2_B, tgt)
        ratio = (T2_B * d) / (T2_B * pred)
        worst = max(worst, abs(ratio - 1))
        print(f"    {m:>3} {tgt:>9.2f} {target_rI:>7.2f} {r:>9.5f} {err:>11.1e} "
              f"{T2_B*d:>10.4f} {T2_B*pred:>10.4f} {ratio:>8.4f}")
    print(f"    -> PRECONDITION 3 (tuning): PASS, every row within 1e-9 of its label")
    print(f"    -> worst departure from Proposition 1 across the four: {worst*100:.2f}%")

    print("\nVERDICT")
    print(f"  Table 1 reproduces the published values to better than 5e-4 on all five rows.")
    print(f"  Table 2 is regenerated at b = {T2_B}: Proposition 1 holds to {worst*100:.2f}% across")
    print("  four configurations sharing no parameter with the one it was matched on. The table")
    print("  this replaces appeared to show 96-99% agreement; that gap was the sampling error of")
    print("  its own estimator, not a departure of Proposition 1.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
